astro_dbt_demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'postgres') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_USER', 'airflow') }}"
      password: "{{ env_var('DBT_PASSWORD', 'airflow') }}"
      dbname: "{{ env_var('DBT_DATABASE', 'airflow') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt_dev') }}"
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DATABASE') }}"
      schema: dbt_prod
      threads: 8
